@startuml
actor User

package System {
  usecase StartGame
  usecase StartGameOnNormalMode
  usecase StartGameOnAdultMode
  usecase StopGame
  usecase GetRandomCardByMode
}

User -- StartGame
StartGame <-- StartGameOnNormalMode
StartGame <-- StartGameOnAdultMode
User -- GetRandomCardByMode
User -- StopGame
StartGame ..> GetRandomCardByMode : <<include>>
@enduml
